version: "3.4"

services:
  influxdb:
    image: influxdb:1.8.10
    container_name: influxdb
    environment:
      - INFLUXDB_DB=metrics
      - INFLUXDB_UDP_PRECISION=s
    ports:
      - 8086:8086
    networks:
      - qametrics

  grafana:
    image: grafana/grafana:8.5.0
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=pricing
      - GF_SECURITY_ADMIN_PASSWORD=pricing
      - GF_USERS_DEFAULT_THEME=dark
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_USERS_ALLOW_ORG_CREATE=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_INSTALL_PLUGINS=marcusolsson-json-datasource
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/
      - ./grafana/conf/grafana.ini:/etc/grafana/grafana.ini
    networks:
      - qametrics
    restart: always
    depends_on:
      - influxdb

  newman:
    image: postman/newman:5.3-alpine
    container_name: newman
    command:
      run qametrics.postman_collection.json
      -e qametrics.postman_environment.json
      -r cli
      --bail
    volumes:
      - ./newman:/etc/newman
    networks:
      - qametrics
    restart: on-failure:1
    depends_on:
      - influxdb
      - grafana

networks:
  qametrics:
    external: false
    driver: bridge
    name: qametrics
