{
 "title": "Jira",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "teamName",
    "label": "Team Name",
    "query": "select distinct teamName from metrics where service = 'jira'"
   },
   {
    "name": "organization",
    "query": "SELECT organization FROM metrics WHERE \"component\" = 'organization' LIMIT 1"
   }
  ]
 },
 "panels": [
  { "title": "Quality Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Created Bugs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT count(id) as bugs from metrics where \"component\" = 'issues' and \"service\" = 'jira' and \"metric\" = 'bugs' and (\"issueType\" = 'Bug' or \"issueType\" = 'Sub-Bug') and \"teamName\" = '$teamName'"
    }
   ]
  },
  {
   "title": "Spent Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT sum(value) as value from metrics where \"component\" = 'issues' and \"service\" = 'jira' and \"metric\" = 'bugs' and (\"issueType\" = 'Bug' or \"issueType\" = 'Sub-Bug') and \"teamName\" = '$teamName' and \"status\" <> 'Cancelled'"
    }
   ]
  },
  {
   "title": "Pending Bugs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT count(id) as bugs from metrics where \"component\" = 'issues' and \"service\" = 'jira' and \"metric\" = 'bugs' and (\"issueType\" = 'Bug' or \"issueType\" = 'Sub-Bug') and \"teamName\" = '$teamName' AND (\"status\" <> 'Done' AND \"status\" <> 'In Production' AND \"status\" <> 'Cancelled')"
    }
   ]
  },
  {
   "title": "Status Progress",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT aggregateProgressPercent from metrics where \"component\" = 'issues' and \"service\" = 'jira' and \"metric\" = 'bugs' and (\"issueType\" = 'Bug' or \"issueType\" = 'Sub-Bug') and \"teamName\" = '$teamName' and \"status\" <> 'Cancelled'"
    }
   ]
  },
  {
   "title": "PROD Bugs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT count(id) as bugs from metrics where \"component\" = 'issues' and \"service\" = 'jira' and \"metric\" = 'bugs' and (\"issueType\" = 'Bug' or \"issueType\" = 'Sub-Bug') and \"teamName\" = '$teamName' AND \"environment\" = 'PROD'  and \"status\" <> 'Cancelled'"
    }
   ]
  },
  {
   "title": "Cancelled Bugs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT count(id) as bugs from metrics where \"component\" = 'issues' and \"service\" = 'jira' and \"metric\" = 'bugs' and (\"issueType\" = 'Bug' or \"issueType\" = 'Sub-Bug') and \"teamName\" = '$teamName' AND \"status\" = 'Cancelled'"
    }
   ]
  },
  {
   "title": "Bug Type",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "query": "SELECT \"bugType\" FROM \"metrics\" WHERE \"component\" = 'issues' AND \"service\" = 'jira'  AND \"metric\" = 'bugs' AND (\"issueType\" = 'Bug' OR \"issueType\" = 'Sub-Bug') AND \"teamName\" = '$teamName' and \"status\" <> 'Cancelled'"
    }
   ]
  },
  {
   "title": "Root Cause",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "query": "SELECT \"rootCause\" FROM \"metrics\" WHERE \"component\" = 'issues' AND \"service\" = 'jira'  AND \"metric\" = 'bugs' AND (\"issueType\" = 'Bug' OR \"issueType\" = 'Sub-Bug') AND \"teamName\" = '$teamName' and \"status\" <> 'Cancelled'"
    }
   ]
  },
  {
   "title": "Environment",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "query": "SELECT \"environment\" FROM \"metrics\" WHERE \"component\" = 'issues' AND \"service\" = 'jira'  AND \"metric\" = 'bugs' AND (\"issueType\" = 'Bug' OR \"issueType\" = 'Sub-Bug') AND \"teamName\" = '$teamName' and \"status\" <> 'Cancelled'"
    }
   ]
  },
  {
   "title": "Bug Type (Workload)",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "query": "SELECT * FROM \"metrics\" WHERE \"component\" = 'issues' AND \"service\" = 'jira'  AND \"metric\" = 'bugs' AND (\"issueType\" = 'Bug' OR \"issueType\" = 'Sub-Bug') AND \"teamName\" = '$teamName' and \"status\" <> 'Cancelled'"
    }
   ]
  },
  {
   "title": "Root Cause (Workload)",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "query": "SELECT * FROM \"metrics\" WHERE \"component\" = 'issues' AND \"service\" = 'jira'  AND \"metric\" = 'bugs' AND (\"issueType\" = 'Bug' OR \"issueType\" = 'Sub-Bug') AND \"teamName\" = '$teamName' and \"status\" <> 'Cancelled'"
    }
   ]
  },
  {
   "title": "Environment (Workload)",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "query": "SELECT * FROM \"metrics\" WHERE \"component\" = 'issues' AND \"service\" = 'jira'  AND \"metric\" = 'bugs' AND (\"issueType\" = 'Bug' OR \"issueType\" = 'Sub-Bug') AND \"teamName\" = '$teamName' and \"status\" <> 'Cancelled'"
    }
   ]
  },
  {
   "title": "Created Bugs",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "query": "SELECT * FROM \"metrics\" WHERE \"component\" = 'issues' AND \"service\" = 'jira'  AND \"metric\" = 'bugs' AND (\"issueType\" = 'Bug' OR \"issueType\" = 'Sub-Bug') AND \"teamName\" = '$teamName' AND \"status\" <> 'Cancelled' ORDER BY DESC"
    }
   ]
  },
  {
   "title": "Required Fields Missing",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "query": "SELECT * FROM metrics WHERE \"teamName\" = '$teamName' AND (\"bugType\" = 'false' or \"environment\" = 'false' or \"rootCause\" = 'false' or \"rootCauseAnalysis\" = 'false') and \"status\" <> 'Cancelled'"
    }
   ]
  }
 ]
}