{
 "title": "Pyramid",
 "time": { "from": "now/y", "to": "now/y" },
 "panels": [
  { "title": "Test Pyramid", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cart Calculator Progress",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT * FROM metrics WHERE component = 'pyramid' AND metric =~ /cart_*/"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 14, "w": 1, "x": 7, "y": 1 } },
  {
   "title": "Charge Progress",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT * FROM metrics WHERE component = 'pyramid' AND metric =~ /charge_*/"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 14, "w": 1, "x": 15, "y": 1 } },
  {
   "title": "Deal Progress",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT * FROM metrics WHERE component = 'pyramid' AND metric =~ /deal_*/"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 14, "w": 1, "x": 23, "y": 1 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "actual",
     "query": "SELECT sum(vo) as initial FROM metrics WHERE component = 'pyramid' AND metric =~ /cart_*/"
    },
    {
     "alias": "current",
     "query": "SELECT sum(value) as current FROM metrics WHERE component = 'pyramid' AND metric =~ /cart_*/"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "actual",
     "query": "SELECT sum(vo) as initial FROM metrics WHERE component = 'pyramid' AND metric =~ /charge_*/"
    },
    {
     "alias": "current",
     "query": "SELECT sum(value) as current FROM metrics WHERE component = 'pyramid' AND metric =~ /charge_*/"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "actual",
     "query": "SELECT sum(vo) as initial FROM metrics WHERE component = 'pyramid' AND metric =~ /deal_*/"
    },
    {
     "alias": "current",
     "query": "SELECT sum(value) as current FROM metrics WHERE component = 'pyramid' AND metric =~ /deal_*/"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT * FROM metrics WHERE component = 'pyramid' AND metric =~ /cart_*/"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 7, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT * FROM metrics WHERE component = 'pyramid' AND metric =~ /charge_*/"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 7, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT * FROM metrics WHERE component = 'pyramid' AND metric =~ /deal_*/"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Price Progress",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT * FROM metrics WHERE component = 'pyramid' AND metric =~ /price_*/"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 14, "w": 1, "x": 7, "y": 22 } },
  {
   "title": "Pricing Engine Progress",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT * FROM metrics WHERE component = 'pyramid' AND metric =~ /pricing_*/"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "actual",
     "query": "SELECT sum(vo) as initial FROM metrics WHERE component = 'pyramid' AND metric =~ /price_*/"
    },
    {
     "alias": "current",
     "query": "SELECT sum(value) as current FROM metrics WHERE component = 'pyramid' AND metric =~ /price_*/"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "actual",
     "query": "SELECT sum(vo) as initial FROM metrics WHERE component = 'pyramid' AND metric =~ /pricing_*/"
    },
    {
     "alias": "current",
     "query": "SELECT sum(value) as current FROM metrics WHERE component = 'pyramid' AND metric =~ /pricing_*/"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT * FROM metrics WHERE component = 'pyramid' AND metric =~ /price_*/"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 7, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT * FROM metrics WHERE component = 'pyramid' AND metric =~ /pricing_*/"
    }
   ]
  }
 ]
}